PATCH  http://localhost:9000/products/643bae14943ed411cdc19a40 HTTP/1.1
content-type: application/json

{
   "name": "IPhone 16",
    "price": 55000000,
    "discount": 10,
    "stock": 3000,
    "categoryId": "6419bcd949d2bc36ded86861",
    "supplierId": "6419c47e49d2bc36ded86868",
    "description" : "DEP"
}
