POST http://localhost:9000/products HTTP/1.1
content-type: application/json

{
    "name": "IPhone 13",
    "price": 25000000,
    "discount": 10,
    "stock": 3000,
    "categoryId": "643bf710269da8d8e40cb227",
    "supplierId": "6419c47e49d2bc36ded86868",
    //"description" : "DEP"
}